import { describe, expect, it } from "bun:test";
import { getTableColumns } from "drizzle-orm";

import {
  issueActivity,
  issueAttachments,
  issueComments,
  issueDependencies,
  issueInbox,
  issueProjects,
  issues,
  issueSessions
} from "../../db/schema";

describe("issues schema coverage", () => {
  it("captures projects, issues, comments, activity, attachments, inbox, dependencies, and sessions", () => {
    expect(Object.keys(getTableColumns(issueProjects))).toEqual([
      "id",
      "tenantId",
      "label",
      "status",
      "ownerKind",
      "ownerId",
      "defaultQueue",
      "issueCount",
      "updatedAt"
    ]);
    expect(Object.keys(getTableColumns(issues))).toEqual([
      "id",
      "tenantId",
      "projectId",
      "title",
      "status",
      "priority",
      "queue",
      "assigneeKind",
      "assigneeId",
      "reporterKind",
      "reporterId",
      "sessionId",
      "runtimeId",
      "labelCount",
      "updatedAt"
    ]);
    expect(Object.keys(getTableColumns(issueComments))).toEqual([
      "id",
      "tenantId",
      "issueId",
      "actorKind",
      "actorId",
      "body",
      "createdAt"
    ]);
    expect(Object.keys(getTableColumns(issueActivity))).toEqual([
      "id",
      "tenantId",
      "issueId",
      "type",
      "summary",
      "createdAt"
    ]);
    expect(Object.keys(getTableColumns(issueAttachments))).toEqual([
      "id",
      "tenantId",
      "issueId",
      "label",
      "uri",
      "kind",
      "createdAt"
    ]);
    expect(Object.keys(getTableColumns(issueInbox))).toEqual([
      "id",
      "tenantId",
      "issueId",
      "queue",
      "reason",
      "ownerId",
      "status",
      "updatedAt"
    ]);
    expect(Object.keys(getTableColumns(issueDependencies))).toEqual([
      "id",
      "tenantId",
      "issueId",
      "blockerIssueId",
      "status",
      "updatedAt"
    ]);
    expect(Object.keys(getTableColumns(issueSessions))).toEqual([
      "id",
      "tenantId",
      "issueId",
      "sessionId",
      "workDir",
      "runtimeId",
      "workspaceId",
      "agentProfileId",
      "status",
      "lastResumedAt",
      "updatedAt"
    ]);
  });
});
